on: [push]
  # schedule:
  #   - cron: '30 5 * * 1,3'
  #   - cron: '30 5 * * 2,4'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'
      - name: install lxml
        run: |
          sudo apt-get install python3-lxml
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r -requirements.txt
      - uses: actions/checkout@v1
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.LITERALLY_ANYTHING }}
      - name: Run utility tool
        working-directory: ./scraper_command_line_utility
        run: |
          python3 -m scraper dog
          git add scraper_command_line_utility/scraper/cache
          git tag run-$(date +%Y%m%d%H%M%S)
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Scheduled update
          branch: github_action_update
          push_options: --force
          skip_dirty_check: true 
          create_branch: true