on: [push]
  # schedule:
  #   - cron: '30 5 * * 1,3'
  #   - cron: '30 5 * * 2,4'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'
      - name: install lxml
        run: |
          sudo apt-get install python3-lxml
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
      - name: run reqs
        run: |
          pip install -r requirements.txt
      - name: Run utility tool
        working-directory: ./scraper_command_line_utility
      - name: Check out code
        uses: actions/checkout@v1
      - name: Create release branch
        run: git checkout -b v${{ github.event.inputs.versionName }}
      - name: Initialize mandatory git config
        run: |
          git config user.name "GitHub Actions"
          git config user.email noreply@github.com
      - name: Commit changelog and manifest files
        # id: make-commit
        run: |
          git add .
          git commit --message "update data with run ${{ github.event.inputs.versionName }}"
          echo "::set-output name=commit::$(git rev-parse HEAD)"
      - name: Push new branch
        run: git push origin v${{ github.event.inputs.versionName }}