on: [push]
  # schedule:
  #   - cron: '30 5 * * 1,3'
  #   - cron: '30 5 * * 2,4'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'
      - name: Install lxml
        run: |
          sudo apt-get install python3-lxml
      - name: Upgrade pip
        run: |
          python -m pip install --upgrade pip
      - uses: actions/checkout@v3
        with:
          token: ${{secrets.LITERALLY_ANYTHING}}
      #     working-directory: ./scraper_command_line_utility
      - name: good lord go
        working-directory: ./scraper_command_line_utility
        run: |
          git checkout github_action_update
          date +'%Y%m%d-%H%M%S' > timestamp.txt
          git config user.name ${{ github.actor }}
          git config user.email krystinv@gmail.com
          git add .
          git commit -m "generated"
          git push origin github_action_update --force





      # - name: fool the system
      #   working-directory: ./scraper_command_line_utility
      #   run: |
      #     git checkout github_action_update

      #     git config --global user.email "krystinv@gmail.com"
      #     git config --global user.name "Krystin Villeneuve"
      #     git add .
      #     git tag run-$(date +%Y%m%d%H%M%S)
      #     git commit -m 'update'
      #     git push origin github_action_update --force
      # - name: Install dependencies
      #   run: |
      #     pip install -r requirements.txt
      # - name: Run utility tool
      #   working-directory: ./scraper_command_line_utility
      #   run: |
      #     python3 -m scraper dog
      #     git add .
      #     git tag run-$(date +%Y%m%d%H%M%S)

        # run: |
          # git config --global user.email "krystinv@gmail.com"
          # git config --global user.name "Krystin Villeneuve"
          # git add .
          # git tag run-$(date +%Y%m%d%H%M%S)
          # git commit -m 'update'
          # git push origin github_action_update --force
      # - uses: stefanzweifel/git-auto-commit-action@v4
      #   with:
      #     commit_message: Scheduled update
      #     branch: github_action_update
      #     commit_user_name: Krystin Villeneuve # defaults to "github-actions[bot]"
      #     commit_user_email: krystinv@gmail.com # defaults to "github-actions[bot]@users.noreply.github.com"
      #     commit_author: krystin987@github.com 
      #     push_options: --force
      #     skip_dirty_check: true 
      #     create_branch: true