on: [push]
  # schedule:
  #   - cron: '30 5 * * 1,3'
  #   - cron: '30 5 * * 2,4'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'
      - name: install lxml
        run: |
          sudo apt-get install python3-lxml
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
      - name: check token
        run: |
            echo: ${{ github.token }}
      - name: Check out code
        uses: actions/checkout@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: Initialize mandatory git config
        run: |
          git config -l
          git config user.name "Krystin Villeneuve"
          git config user.email krystinv@gmail.com
      - name: Create data update branch
        run: git checkout github_actions
        run: |
          pip install -r requirements.txt
      - name: Run utility tool
        working-directory: ./scraper_command_line_utility
        run: python3 -m scraper dog
      - name: Commit changelog and manifest files
        id: make-commit
        run: |
          git add .
          git commit --message "update data with run ${{ github.event.inputs.versionName }}"
          echo "::set-output name=commit::$(git rev-parse HEAD)"
      - name: Remove remote
        run: git remote rm origin
      - name: Add remote
        run: git remote add origin git@github.com:krystin987/scrape-attack.git
      - name: Push new branch
        run: git push origin github_action_update