on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'
      - name: install lxml
        run: |
          sudo apt-get install python3-lxml
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
      - name: Install NLKT   
        run: |
          echo -e "import nltk\nnltk.download('punkt')" | python3
      - name: run reqs
        run: |
          pip install -r requirements.txt
      - name: Run utility tool
        working-directory: ./scraper_command_line_utility
        run: python3 -m scraper dog