on:
  schedule:
    - cron: '46 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'
      - name: Install lxml
        run: |
          sudo apt-get install python3-lxml
      - name: Upgrade pip
        run: |
          python -m pip install --upgrade pip
      - uses: actions/checkout@v3
        with:
          token: ${{secrets.MY_SECRET_NAME}}
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - uses: actions/checkout@v3
        with:
          token: ${{secrets.MY_SECRET_NAME}}
      - name: commit and whatnot
        working-directory: ./scraper_command_line_utility
        run: |
          git checkout actions_run
          git tag ${{ github.run_id }}
          git config user.name ${{ github.actor }}
          git config user.email ${{secrets.EMAIL}}
          python3 -m scraper dog
          git add .
          git commit -m "generated"
          git push --set-upstream origin actions_run --force