on: [push]
  # schedule:
  #   - cron: '30 5 * * 1,3'
  #   - cron: '30 5 * * 2,4'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'
      - name: install lxml
        run: |
          sudo apt-get install python3-lxml
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
      - name: run reqs
        run: |
          pip install -r requirements.txt
      # - uses: actions/checkout@v2
      #     persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
      #     fetch-depth: 0
      - name: Run utility tool
        working-directory: ./scraper_command_line_utility
        run: python3 -m scraper dog
      - name: Commit files
        run: |
          git commit -a -m "update data"
      - name: Push changes
        uses: ad-m/github-push-action@github_actions_update
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
      # - name: Create branch and commit
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     add: '.'
      #     default_author: github_actions
      #     message: 'update article data'
      #     new_branch: updated-gh-actions
      #     push: origin updated-gh-actions --set-upstream --force